# railway.toml
[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
  name = "web"
  region = "us-east"
  plan = "starter"
  autoDeploy = true

[[corsOrigins]]
  origin = "https://*.anuntech.com"
  methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowCredentials = true
  headers = ["Content-Type", "Authorization"]